spring:
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: test-service
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/test-service/**
          filters:
            - name: Hystrix
              args:
                name: fetchIngredients
                fallbackUri: forward:/fallback

        - id: fallback
          uri: http://localhost:8080
          predicates:
            - Path=/fallback

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

server:
  port: 8080